spring:
  datasource:
    url: jdbc:mysql://localhost:3306/weike?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  servlet:
    multipart:
      enabled: true
mybatis:
  type-aliases-package: com.dlg.proj.demo.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

